export interface Devs {
    
     // Generated by https://quicktype.io


    complete: Complete[];
   
}

export interface Complete {
    firstName:  string;
    lastName:   string;
    innovation: string;
    year:       number;
}




